### PR TITLE
Update tabler.min.css pagination class flex-wrap

### PR DESCRIPTION
**Pull request by randomactsofsecurity**
Added the flex-wrap: wrap directive to the CSS for the .pagination class, which helps with the wrapping of pages at the bottom of the gowitness html report.

Before change, the pages would keep in a row moving beyond the page and adding in a scroll bar.

image

Now, the page properly wraps depending on the viewport size (smaller window, more page # rows etc).

image

image

### CODE REVIEW

**Comment by leonjza** [comment]
Can we chance this PR so that we import an override `.css` file, making future upgrades of the Tabler CSS not throw this change away?

**Comment by randomactsofsecurity** [comment]
What's the source of the tabler.min.css? I can't find the original file that's included here https://github.com/tabler/tabler/releases?page=3 ( can't seem to find release 1.0.0-alpha.7).  Also seems like the tabler.min.js file that you include is super cut down, did you originally manually remove a bunch of the JS to minify it even more?  I know the JS/CSS for Tabler has been updated quite a bit (which breaks some of the initial UI just swapping the latest CDN CSS in)

**Comment by leonjza** [comment]
A good question. I think the best action here is to bump to the latest release and then check what edits we need from there.

**Comment by randomactsofsecurity** [comment]
Yeah, I'm not entirely sure where it came from or why it's so condensed. Either way, after looking into this I have no idea why I didn't just put the fix within the HTML, so I'm going to close this one out. I may open a PR soon with some new HTML sorting features, so I'll include a bump in the CSS/JS with it since it does need those features.

**Pull request closed without merging**
